// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    rental_contract
    (
        init => init
        upgrade => upgrade
        createRentalContract => create_rental_contract
        acceptContract => accept_contract
        makePayment => make_payment
        landlordDecision => landlord_decision
        tenantDecision => tenant_decision
        getContractDetails => get_contract_details
        getContractsByLandlord => get_contracts_by_landlord
        getContractsByTenant => get_contracts_by_tenant
        getDepositDecisionDetails => get_deposit_decision_details
        getPaymentsStatus => get_payments_status
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
